name: "Pace main tests"
on:
  push:
  pull_request:

jobs:
  pace_main_tests:
    uses: mlee03/pace/.github/workflows/main_unit_tests.yaml@reusable_workflow
    with:
      component_trigger: true
      component_name: pyFV3
