name: "pySHiELD translate tests"
on:
  push:
  pull_request:

jobs:
  pyshield_translate_tests:
    uses:  mlee03/PySHiELD/.github/workflows/translate.yaml@reusing_workflows
    with:
      component_trigger: true
      component_name: pyFV3
